Controllers/EvaluationController.cs
using AppointmentK1.Models;
using AppointmentK1.Models.Custom;
using SVM.Communication;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Xml.Serialization;

namespace AppointmentK1.Controllers
{
    public class EvaluationController : Controller
    {
        public Student student;
        // GET: Evaluation
        [SDAuthorize]
        public ActionResult Evaluate()
        {
            ViewData["imgsrc"] = Logo();
            ViewData["Student"] = GetStudent();
            DrivingToEvaluate dte = GetDrivingToEvaluate();
            if (dte != null)
            {
                ViewData["DrivingToEvaluate"] = dte;
                return View();

            }
            else { return View("NothingToRate"); }
        }
        public ActionResult Message(string message)
        {
            ViewBag.Message = message;
            return PartialView("_Message");
        }
        public string Logo()
        {
            DSConfigurator dsc = new DSConfigurator();
            return dsc.Logo;
        }
        public ActionResult SendRating(int mark, string comment)
        {
            Student st = GetStudent();
            DrivingToEvaluate dte = (DrivingToEvaluate)Session["DrivingToEvaluate"];
            ServiceSpeaker srsp = new ServiceSpeaker(ServiceSpeaker.ConstructionMode.fromFile, @"D:\SvmWcf.xml");
            Dictionary<string, string> spParams = new Dictionary<string, string>()
            {
                ["IdDriving"] = dte.Id.ToString(),
                ["IdCategory"] = "1",
                ["IdStudent"] = st.Id.ToString(),
                ["Mark"] = mark.ToString(),
                ["Comment"] = comment
            };
            string Result = srsp.Fetch("spSDWriteDrivingRating", spParams);
            return Message("Спасибо за оценку!");
        }
        public Student GetStudent()
        {
            return student = (Student)Session["Student"];
        }
        public DrivingToEvaluate GetDrivingToEvaluate()
        {
            student = (Student)Session["Student"];
            ServiceSpeaker srsp = new ServiceSpeaker(ServiceSpeaker.ConstructionMode.fromFile, @"D:\SvmWcf.xml");
            Dictionary<string, string> spParams = new Dictionary<string, string>() { ["Param"] = student.Id.ToString() };
            string dteinfo = srsp.Fetch("spSDGetDrivingToEvaluateByIdStudent", spParams);
            DrivingToEvaluate dte;
            if (dteinfo.Length > 0)
            {
                using (MemoryStream ms = new MemoryStream(Encoding.UTF8.GetBytes(dteinfo)))
                {
                    dte = (DrivingToEvaluate)(new XmlSerializer(typeof(DrivingToEvaluate)).Deserialize(ms));
                }
                WriteDTE(dte);
            }
            else { dte = null; }
            return dte;
        }
        private void WriteDTE(DrivingToEvaluate dte)
        {
            Session["DrivingToEvaluate"] = dte;
        }
    }
}

Controllers/MyScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AppointmentK1.Models.Custom;
using AppointmentK1.Models;

namespace AppointmentK1.Controllers
{
    public class MyScheduleController : Controller
    {
        public Student student;
        // GET: MySchedule
        [SDAuthorize]
        public ActionResult Index()
        {
            student = GetStudent();
            ViewData["Student"] = student;
            ViewData["imgsrc"] = Logo();
            List<Driving> Drivings = student.ShowMySchedule().Drivings;
            return View(Drivings);
        }
        public Student GetStudent()
        {
            return (Student)Session["Student"];
        }
        public string Logo()
        {
            DSConfigurator dsc = new DSConfigurator();
            return dsc.Logo;
        }
    }
}

Views/Shared/DSLayout.cshtml
@{
    string imgsrc = ViewData["imgsrc"] as string;
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Вождение - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><img src="@imgsrc" class="image-responsive" /></a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="#"><strong>@ViewBag.Student</strong></a></li>
                    <li><a href="@Url.Action("Show", "Schedule")">Запись на вождение</a></li>
                    <li><a href="@Url.Action("Index", "MySchedule")">Моё расписание</a></li>
					<li><a href="@Url.Action("Evaluate", "Evaluation")">Оценить</a></li>
                    <li><a href="@Url.Action("Exam", "Exam")">Мои экзамены</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="@Url.Action("Logout", "Home")"><span class="glyphicon glyphicon-log-out"></span> Выход</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <div class="jumbotron">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery-ui")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jquery-unobtrusive-ajax")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/Entrance.cshtml
@{ 
    string imgsrc = ViewData["imgsrc"] as string;
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Вождение - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#"><img src="@imgsrc" class="image-responsive" /></a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <h1>Вождение</h1>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <div class="jumbotron">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("О программе", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>